services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=nina-service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - jaeger
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
    ports:
      - "16686:16686"
      - "4317"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  worker:
    build: .
    environment:
      - OTEL_SERVICE_NAME=nina-service-worker
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=console
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    command: ["uv", "run", "celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
