services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=nina-service
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=console
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
