services:
  api:
    build:
      context: .
      target: dev # Para reload com --watch
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=obs-api
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp,console
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4317
      - OTEL_PYTHON_EXCLUDED_URLS=health
      - OTEL_METRIC_EXPORT_INTERVAL=5000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=3)"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    develop:
      watch:
        - action: sync+restart # Copia só os arquivos alterados para dentro do container em execução, sem criar imagem nova
          path: .
          target: /app
          ignore:
            - pyproject.toml
            - uv.lock
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
    depends_on:
      - lgtm
  lgtm:
    image: grafana/otel-lgtm:0.33.0   # fixe a versão
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
